# Generated by Django 3.1.2 on 2020-10-30 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_auto_20201028_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='is_member',
            field=models.BooleanField(default=False),
        ),
    ]
