# Generated by Django 3.1.2 on 2021-02-14 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_auto_20210213_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_baptized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='is_married',
            field=models.BooleanField(default=False),
        ),
    ]
