# Generated by Django 3.1.2 on 2021-02-15 05:19

from django.db import migrations, models
import finance.models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_auto_20210214_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='education',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='year_joined',
            field=models.IntegerField(default=finance.models.current_year, max_length=4),
        ),
    ]
