# Generated by Django 3.1.2 on 2021-03-26 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_auto_20210215_0819'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['-created_at', '-id'], 'verbose_name_plural': 'Entries'},
        ),
        migrations.AlterField(
            model_name='entity',
            name='person',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.person'),
        ),
    ]
