# Generated by Django 3.1.2 on 2021-03-26 11:58

from django.db import migrations, models
import finance.models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_auto_20210326_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='year_joined',
            field=models.IntegerField(default=finance.models.current_year),
        ),
    ]
