# Generated by Django 3.1.2 on 2021-04-02 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
        ('finance', '0013_auto_20210326_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='entity',
            name='person',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.person'),
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
