# Generated by Django 3.1.2 on 2021-04-02 09:21

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], default='M', max_length=2)),
                ('is_married', models.BooleanField(default=False)),
                ('is_baptized', models.BooleanField(default=False)),
                ('year_joined', models.IntegerField(default=core.models.current_year)),
                ('education', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
