# Generated by Django 3.1.2 on 2021-04-03 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210402_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='rank',
            field=models.IntegerField(default=99),
        ),
    ]
