# Generated by Django 3.1.2 on 2021-04-03 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210403_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='type',
            field=models.CharField(choices=[('BARAZA KUU', 'BARAZA KUU'), ('UONGOZI', 'UONGOZI'), ('IDARA', 'IDARA'), ('SELI', 'SELI')], max_length=100),
        ),
    ]
