# Generated by Django 3.1.2 on 2021-04-12 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210403_1016'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='admin/batch')),
                ('status', models.CharField(choices=[('Initiated', 'Initiated'), ('Processed', 'Processed')], default='Initiated', max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['rank']},
        ),
    ]
