# Generated by Django 3.1.2 on 2021-04-12 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210412_1458'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch',
            options={'verbose_name_plural': 'Batches'},
        ),
        migrations.AddField(
            model_name='batch',
            name='message',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
