# Generated by Django 3.1.2 on 2021-04-12 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210412_1722'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='batch',
        #     name='created_at',
        #     field=models.DateTimeField(auto_created=True, default=None),
        #     preserve_default=False,
        # ),
    ]
