# Generated by Django 3.1.2 on 2021-04-13 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210412_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
